# Development environment
version: '3.8'

services:
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/*/node_modules
    ports:
      - "3000:3000"   # Main SaaS app
      - "3001:3001"   # Secondary SaaS app
      - "8000:8000"   # AI services
      - "8001:8001"   # Secondary AI service
      - "9000:9000"   # Tools/utilities
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in containers
    command: npm run dev

  # Development database
  dev-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: luxoranova9_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5433:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data

  # Development Redis
  dev-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - dev_redis_data:/data

volumes:
  dev_postgres_data:
  dev_redis_data: